### ISSUE TITLE
Error processing datetime value

### ISSUE THREAD

**Issue by allurefx** [pacman82/arrow-odbc#104]
Hi, I'm running into an error when processing the below datetime value from MSSQL:
`year = 9999
month = 12
day = 31
hour = 23
minute = 59
second = 59
fraction = 999999900`

The error says: "invalid value object" and I traced it down to line 155 of fill_arrow_array(). Other dates worked fine, this extreme value seems to be causing problems. I'd appreciate any help running this down, thanks.

**Comment by allurefx** [comment]
I noticed that years of up to 2261 work with these month/date/etc., but 2262 and up fail.

**Comment by pacman82** [comment]
Hello @allurefx ,

yeah, this value is simply out of range and can not be represented by the associated arrow type. I can improve the error message though. If a logging backend is registered, could you share the log messages with me? I would like to know the database types involved.

**Comment by allurefx** [comment]
Thanks @pacman82. The issue isn't so much that it can't be interpreted, but that the entire next() call is erroring out so I can't get any column if there is one column with a bad date value. Right now, I'm unable to push this for production since SQL like SELECT * fails. If you could default where there is a bad value rather than throw an error, that would be great. Or perhaps you have a workaround or suggestion? The driver is ODBC Driver 18 for SQL Server, I don't see any errors in the log.

**Comment by pacman82** [comment]
Hello @allurefx ,

I would still like to see the logs, to learn about the involved data types. We might get this to work, but I currently do not want to guess the exeuction path. If a log backend is registered with info level, I'll be able to gather all the information needed.

Alternatively, even the stacktrace from the panic is helpful. Please share this information.

Best, Markus

**Comment by allurefx** [comment]
There is no panic, next() returns None. But here's the log when level is set to debug, hope this helps.

SQLAllocHandle allocated connection (Dbc) handle '0x73ff300181d0'
State: 01S00, Native error: 0, Message: [Microsoft][ODBC Driver 18 for SQL Server]Invalid connection string attribute
State: 01000, Native error: 5701, Message: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Changed database context to 'WideWorldImporters-Standard'.
State: 01000, Native error: 5703, Message: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Changed language setting to us_english.
ODBC driver reported for column 0. Relational type: Timestamp { precision: 7 }; Nullability: NoNulls; Name: 'ValidTo';
Column 'ValidTo'
Bytes used per row: 16
Total memory usage per row for single transit buffer: 16
Entering GC root set LIFO scope: 0
Exiting GC root set LIFO scope: 0
SQLFreeHandle dropped 0x73ff3017a050 of type Stmt.
SQLFreeHandle dropped 0x73ff300181d0 of type Dbc.

**Comment by pacman82** [comment]
Thanks for the log and the additional information. It seems to me that before the the iterator which yields `None` you should have gotten one `Err` with this error:

https://github.com/pacman82/arrow-odbc/blob/08c5de1b5e5f1b3c4e0f47d1fe9d0cc7d77c7c20/src/reader/map_odbc_to_arrow.rs#L202

Would you have any chance to clamp the values, or filter map the values larger than valid dates to `Null` in the query?

**Comment by pacman82** [comment]
Here the entire text of the error message:

> Timestamp is not representable in arrow: {value}
> Timestamps with nanoseconds precision are represented using a signed 64 Bit integer. This limits their range to values between 1677-09-21 00:12:44 and 2262-04-11 23:47:16.854775807. The value returned from the database is outside of this range. Suggestions to fix this error either reduce the precision or fetch the values as text.

**Comment by pacman82** [comment]
@allurefx You may be happy to learn that `arrow-odbc 12.0.0` has been released. It features a new method for the `OdbcReaderBuilder` called `value_errors_as_null`. Setting the attribute to `true` should yield the behavior you desire.

Best, Markus

**Comment by allurefx** [comment]
Thank you @pacman82, I will try that out.
