### ISSUE TITLE
[Feature Request] Convert Schema string from ODBC to ArrowSchema from pub API

### ISSUE THREAD

**Issue by hu6360567** [pacman82/arrow-odbc#4]
Any plan on api to get tables and schemas from odbc connection?

**Comment by pacman82** [comment]
The new `arrow_schema_from` function would allow you to get the schema from a prepared query, without executing it. This would get rid of a previously required workaround sending a dummy query like "`SELECT * FROM MyTable WHERE 1=2`". Keep in mind though, while the ODBC driver may do something clever, maybe it now just does that workaround itself.

See this code sample regarding your orginial question: <https://docs.rs/arrow-odbc/0.5.0/arrow_odbc/fn.arrow_schema_from.html>

```rust
use anyhow::Error;
 
use arrow_odbc::{arrow_schema_from, arrow::datatypes::Schema, odbc_api::Connection};
 
fn fetch_schema_for_table(
    table_name: &str,
    connection: &Connection<'_>
) -> Result<Schema, Error> {
    // Query column with values to get a cursor
    let sql = format!("SELECT * FROM {}", table_name);
    let prepared = connection.prepare(&sql)?;
     
    // Now that we have prepared statement, we want to use it to query metadata.
    let schema = arrow_schema_from(&prepared)?;
    Ok(schema)
}
```
