### ISSUE TITLE
ADBC support?

### ISSUE THREAD

**Issue by aersam** [pacman82/arrow-odbc#61]
Just an idea: would be nice to use this as a bridge from odbc to adbc

https://arrow.apache.org/adbc/0.5.1/format/specification.html 

Feel free to close this if too complex / time consuming or otherwise not wanted

Would probably need to use this lib: https://github.com/apache/arrow-adbc/blob/main/rust/Cargo.toml

**Comment by pacman82** [comment]
Hello @aersam ,

an odbc adbc bridge would be indeed nice, but I also feel it would be its own artefact to not introduce unnecessary overhead. IMHO `adbc` should change its design to rely on a C-Interface to talk between db-driver and language bindings anyway. This way each db backend wouldn't need to be implemented for every language, but only with the C-Interface once.

What being said if somebody wants to try and go about this, I am happy to help and answer questions, but also given my current spare time I do not see myself embarking on this endavour.

Best, Markus
