### ISSUE TITLE
about ConcurrentOdbcReader send

### ISSUE THREAD

**Issue by web3creator** [pacman82/arrow-odbc#83]
### problem
This is the problem I'm having
```
error[E0277]: `(dyn arrow_odbc::reader::ReadStrategy + 'static)` cannot be sent between threads safely
   --> src/odbc/odbc_drive.rs:105:25
    |
105 |                 Ok(Some(Box::pin(s)))
    |                         ^^^^^^^^^^^ `(dyn arrow_odbc::reader::ReadStrategy + 'static)` cannot be sent between threads safely
    |
    = help: the trait `std::marker::Send` is not implemented for `(dyn arrow_odbc::reader::ReadStrategy + 'static)`
    = note: required for `std::ptr::Unique<(dyn arrow_odbc::reader::ReadStrategy + 'static)>` to implement `std::marker::Send`
note: required because it appears within the type `Box<dyn ReadStrategy>`
   --> /Users/simonyi/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:195:12
```

### where
Can it be changed?
[impl<C: Cursor + Send + 'static> ConcurrentOdbcReader<C> {](https://github.com/pacman82/arrow-odbc/blob/194ed957cf49d073b0de728722858072fa09ee87/src/reader/concurrent_odbc_reader.rs#L85) 

### I think

I think it is better to use SendableRecordBatchStream type here
```
pub trait RecordBatchStream: Stream<Item = Result<RecordBatch>> {
    fn schema(&self) -> SchemaRef;
}

pub type SendableRecordBatchStream = Pin<Box<dyn RecordBatchStream + Send>>;
```

**Comment by pacman82** [comment]
What is the piece of code which causes the compiler error trying to achieve?

**Comment by web3creator** [comment]
@pacman82 
```
use std::{
    pin::Pin,
    task::{Context, Poll},
};

use arrow_array::{RecordBatch, RecordBatchReader};
use arrow_odbc::{odbc_api::Cursor, ConcurrentOdbcReader};
use arrow_schema::SchemaRef;
use datafusion::{error::DataFusionError, physical_plan::RecordBatchStream};
use futures::Stream;


pub struct ExternalTableRecordBatchStream<C: Cursor>  {
    reader: ConcurrentOdbcReader<C> 
}

impl<C: Cursor + Send + 'static> ExternalTableRecordBatchStream<C> {
    pub fn new(reader:ConcurrentOdbcReader<C>) -> Self {
        Self { reader}
    }
}

impl<C: Cursor + Send + 'static> RecordBatchStream for ExternalTableRecordBatchStream<C> {
    fn schema(&self) -> SchemaRef {
        self.reader.schema()
    }
}

impl<C: Cursor + Send + 'static> Stream for ExternalTableRecordBatchStream<C> {
    type Item = datafusion::error::Result<RecordBatch>;

    fn poll_next(mut self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let result = self.reader.next();
        match result {
            Some(Ok(batch)) => Poll::Ready(Some(Ok(batch))),
            Some(Err(e)) => Poll::Ready(Some(Err(DataFusionError::from(e)))),
            None => Poll::Ready(None),
        }

    }
}
```
      fn record_batch_stream(
        &self,
        state: &SessionState,
        projection: Option<&Vec<usize>>,
        filter: &[Expr],
        limit: Option<usize>,
    ) -> Result<SendableRecordBatchStream, datafusion::error::DataFusionError> {
        let sql = format!("SELECT * FROM {}", self.table_ref);
        let reader: arrow_odbc::ConcurrentOdbcReader<arrow_odbc::odbc_api::CursorImpl<arrow_odbc::odbc_api::StatementConnection<'_>>>= self
            .drive
            .odbc_reader_executor(&sql)
            .map_err(|e| DataFusionError::Execution(e.to_string()))?.unwrap().into_concurrent().unwrap();

// error 
  // `(dyn arrow_odbc::reader::ReadStrategy + 'static)` cannot be sent between threads safely
        // the trait `std::marker::Send` is not implemented for `(dyn arrow_odbc::reader::ReadStrategy + 'static)`
        // required for `std::ptr::Unique<(dyn arrow_odbc::reader::ReadStrategy + 'static)>` to implement `std::marker::Send`
        // required for `std::ptr::Unique<Box<(dyn arrow_odbc::reader::ReadStrategy + 'static)>>` to implement `std::marker::Send`
        // required for the cast from `Pin<Box<ExternalTableRecordBatchStream<CursorImpl<StatementConnection<'_>>>>>` to `Pin<Box<dyn RecordBatchStream<Item = std::result::Result<arrow_array::RecordBatch, DataFusionError>> + std::marker::Send>>`rustc
       
       Ok(Box::pin(ExternalTableRecordBatchStream::new(reader)))
        
    }

```

**Comment by web3creator** [comment]
@pacman82  This is demo
https://github.com/web3creator/temp/blob/3dbb83ad8940352eeb1a1b408d390bb9dc1338c8/src/odbc.rs#L87

**Comment by web3creator** [comment]
I hope to return the SendableRecordBatchStream data type. I tried tokio::channel but it still didn’t work. I think it may be necessary to make some changes to arrow-odbc.
```
 fn record_batch_stream(
        &self,
        sql: &str,
    ) -> Result<SendableRecordBatchStream, datafusion::error::DataFusionError> {
        let connection = ODBC_ENVIRONMENT
            .connect_with_connection_string(&self.connection_info, ConnectionOptions::default())
            .unwrap();
        let cursor = connection.into_cursor(sql, ()).unwrap().unwrap();

        let reader = OdbcReaderBuilder::new()
            .with_max_num_rows_per_batch(WITH_MAX_NUM_ROWS_PER_BATCH)
            .build(cursor).unwrap()
            .into_concurrent()
            .unwrap();
        Ok(Box::pin(ExternalTableRecordBatchStream::new(reader)))
    }
```

**Comment by pacman82** [comment]
I could probably add six characters to my Codebase and make your code compile and (seemingly) work. **But**, I do not think I would do you a favor. The call to `next()` within the reader implementation is blocking. The `poll_next` method must not block. It should not only return `None` if the stream runs out of batches, but also if one is not available right now. I would encourage you to go back to the actor approach. Run the `OdbcReader` in its own dedicated system thread and communicate its result via channels to the rest of the application.

I would also suggest not to use the `ConcurrentOdbcReader`, but rather base your design on `OdbcReader`. You can actually use the implementation of `ConcurrentOdbcReader` to create an `AsyncOdbcReader` by copying the implementation and replace the sync to sync channel communication with sync to async.

I would consider doing this myself in the `arrow-odbc` crate, but I am lacking the time to do so in the near future at least.

Right now making `OdbcReader` or `ConcurrentOdbcReader` `Send` would make your code compile, but just go further down a design route, which would not work well with an asynchronous runtime which is backed by only one system thread, and would even become blocking on multithreaded system if just enough instances of these futures are running.

**Comment by web3creator** [comment]
@pacman82 you are right,
I think the following solution is a better solution at present，It seems that if I want to implement async, I need to use copy recordbatch to buffer.
```
let (tx,rx)=mpsc::channel::<result<Recordbatch,ArrowError>>(100);
tokio:swan(async move{
    let result=odbcxxxxxxxx;
  // OdbcReader or ConcurrentOdbcReader will not work here.Because it must be satisfied here,
  //  F: Future<Output = ()>,
  //  F: Send + 'static,
   tx.send(result).await;
})


let stream = async_stream::stream! {
    while let Some(item) = rx.recv().await {
        yield item;
    }
};
```



```
