### ISSUE TITLE
ReadStrategy is not Send

### ISSUE THREAD

**Issue by allurefx** [pacman82/arrow-odbc#92]
Is the ConcurrentOdbcReader thread safe? I'm getting an error saying that ReadStrategy is not Send:
`error[E0277]: `(dyn arrow_odbc::reader::ReadStrategy + 'static)` cannot be sent between threads safely`

Is there a way to use this concurrently? I'm trying to use this with the new WASI component model, saving the reader across multiple calls from the component.

**Comment by pacman82** [comment]
Hello @allurefx ,

`arrow-odbc 8.2.0` has been released. `ConcurrentOdbcReader` is now `Send`. However this is most likely only the beginning of your trouble. I am not sure you can link against `libodbc.so` in the environment you are in.

Best, Markus

**Comment by allurefx** [comment]
Awesome, @pacman82 for the quick turnaround, the error is gone. All the actual ODBC access is on the host side (regular server) and the data (as Arrow batches) is processed inside the WASI component, which is WASM (also via Rust). The idea is to have customers potentially supply these components to do additional processing on the data. I've passed this hurdle, let's see.

**Comment by pacman82** [comment]
Closing the issue then and best of luck
