### ISSUE TITLE
8.3.0: the trait `arrow_odbc::odbc_api::Cursor` is not implemented

### ISSUE THREAD

**Issue by allurefx** [pacman82/arrow-odbc#94]
The 8.3.0 update is breaking my code with:
the trait `arrow_odbc::odbc_api::Cursor` is not implemented for `odbc_api::CursorImpl<odbc_api::StatementConnection<'static>>`

**Comment by pacman82** [comment]
Sounds like a version mismatch for me. Are you sure that the `Cursor` trait and the implementation use the same version of `odbc-api`? Maybe check with `cargo tree` if there are two version of `odbc-api` in your stack.

**Comment by pacman82** [comment]
FYI: `arrow-odbc` reexports `odbc-api` so you can make sure you are always using the same version throughout your application.

**Comment by pacman82** [comment]
Not sure what I can do here, rather than being a bit more explicit in the documentation. Hmm, 🤔 ...

**Comment by pacman82** [comment]
How do you like the new Readme?

**Comment by allurefx** [comment]
Yeah, I think that comment will help, thanks.
