### ISSUE TITLE
how to execute multi-statements where intermediate results don't return a cursor? 

### ISSUE THREAD

**Issue by matthewgapp** [pacman82/arrow-odbc#98]
Hey @pacman82, how would I execute a multi-statement query like below? Based on the documentation and integration tests, you expect a cursor to be returned (only when each statement returns at least one row). 

How would you advise me on how to get something like this to execute (where intermediate results don't return anything and the last result does)? 

```sql
USE DATABASE PAYMENTDATA;

SELECT * FROM "PAYMENTSCHEMA"."CUSTOMERS" LIMIT 10
```

**Comment by pacman82** [comment]
The interface is not really designed for this. I originally imagined `arrow-odbc` much smaller in scope. It does have however the ability to iterate through multiple result sets. You can try though just combining both statements in one SQL text seperated by semicolon (`;`), as in 'USE DATABASE PAYMENTDATA; SELECT * FROM "PAYMENTSCHEMA"."CUSTOMERS" LIMIT 10`. Depending on your ODBC driver this might be fine. If it is you can iterate through result sets using `.more_results`. Whether or not you will have to skip an empty result set, or you get the one you want right away, would also depend on your database driver.

Give it a shot.

**Comment by matthewgapp** [comment]
thanks @pacman82 for  the heads up on the interface design! I've worked around it by executing each statement against the same connection handle. As always, I appreciate the help.

**Comment by pacman82** [comment]
Oh, right. Sorry my mistake. This is the Rust crate, not the Python bindings. Executing it using the same connection is the right thing to do. If you want to inch out a bit more performance you can try reusing the statement handle using preallocated handles. See: <https://docs.rs/odbc-api/latest/odbc_api/struct.Preallocated.html>
